affine_trainable: true
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 30
grid_eps: 1.0
grid_margin: 1.0
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 0
symbolic.funs_name.0:
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.1:
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.2:
- - '0'
  - '0'
  - '0'
  - '0'
symbolic_enabled: true
width:
- - 4
  - 0
- - 4
  - 0
- - 4
  - 0
- - 1
  - 0
